/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSuccessRouteImport } from './routes/store_.success'
import { Route as StoreSlugRouteImport } from './routes/store_.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedViralLabRouteImport } from './routes/_authenticated/viral-lab'
import { Route as AuthenticatedUsageRightsRouteImport } from './routes/_authenticated/usage-rights'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeriesBuilderRouteImport } from './routes/_authenticated/series-builder'
import { Route as AuthenticatedSeoKeywordsRouteImport } from './routes/_authenticated/seo-keywords'
import { Route as AuthenticatedResponseWriterRouteImport } from './routes/_authenticated/response-writer'
import { Route as AuthenticatedRejectionRecoveryRouteImport } from './routes/_authenticated/rejection-recovery'
import { Route as AuthenticatedRecyclerRouteImport } from './routes/_authenticated/recycler'
import { Route as AuthenticatedProfileAuditRouteImport } from './routes/_authenticated/profile-audit'
import { Route as AuthenticatedPostTimingRouteImport } from './routes/_authenticated/post-timing'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedPinOptimiserRouteImport } from './routes/_authenticated/pin-optimiser'
import { Route as AuthenticatedPassiveIdeasRouteImport } from './routes/_authenticated/passive-ideas'
import { Route as AuthenticatedMotivationRouteImport } from './routes/_authenticated/motivation'
import { Route as AuthenticatedMediaKitRouteImport } from './routes/_authenticated/media-kit'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedIncomeTrackerRouteImport } from './routes/_authenticated/income-tracker'
import { Route as AuthenticatedGrowthCoachRouteImport } from './routes/_authenticated/growth-coach'
import { Route as AuthenticatedGeneratorRouteImport } from './routes/_authenticated/generator'
import { Route as AuthenticatedFlopAnalyserRouteImport } from './routes/_authenticated/flop-analyser'
import { Route as AuthenticatedFilmThisRouteImport } from './routes/_authenticated/film-this'
import { Route as AuthenticatedEngagementBoosterRouteImport } from './routes/_authenticated/engagement-booster'
import { Route as AuthenticatedDeliverablesBuilderRouteImport } from './routes/_authenticated/deliverables-builder'
import { Route as AuthenticatedCtaGeneratorRouteImport } from './routes/_authenticated/cta-generator'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedBrollRouteImport } from './routes/_authenticated/broll'
import { Route as AuthenticatedBrandHubRouteImport } from './routes/_authenticated/brand-hub'
import { Route as AuthenticatedBioOptimiserRouteImport } from './routes/_authenticated/bio-optimiser'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAffiliatesRouteImport } from './routes/_authenticated/affiliates'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin_.products'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTrialRemindersRouteImport } from './routes/api/public/hooks/trial-reminders'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSuccessRoute = StoreSuccessRouteImport.update({
  id: '/store_/success',
  path: '/store/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store_/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedViralLabRoute = AuthenticatedViralLabRouteImport.update({
  id: '/viral-lab',
  path: '/viral-lab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRightsRoute =
  AuthenticatedUsageRightsRouteImport.update({
    id: '/usage-rights',
    path: '/usage-rights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeriesBuilderRoute =
  AuthenticatedSeriesBuilderRouteImport.update({
    id: '/series-builder',
    path: '/series-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeoKeywordsRoute =
  AuthenticatedSeoKeywordsRouteImport.update({
    id: '/seo-keywords',
    path: '/seo-keywords',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResponseWriterRoute =
  AuthenticatedResponseWriterRouteImport.update({
    id: '/response-writer',
    path: '/response-writer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRejectionRecoveryRoute =
  AuthenticatedRejectionRecoveryRouteImport.update({
    id: '/rejection-recovery',
    path: '/rejection-recovery',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecyclerRoute = AuthenticatedRecyclerRouteImport.update({
  id: '/recycler',
  path: '/recycler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileAuditRoute =
  AuthenticatedProfileAuditRouteImport.update({
    id: '/profile-audit',
    path: '/profile-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPostTimingRoute = AuthenticatedPostTimingRouteImport.update({
  id: '/post-timing',
  path: '/post-timing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPinOptimiserRoute =
  AuthenticatedPinOptimiserRouteImport.update({
    id: '/pin-optimiser',
    path: '/pin-optimiser',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPassiveIdeasRoute =
  AuthenticatedPassiveIdeasRouteImport.update({
    id: '/passive-ideas',
    path: '/passive-ideas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMotivationRoute = AuthenticatedMotivationRouteImport.update({
  id: '/motivation',
  path: '/motivation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaKitRoute = AuthenticatedMediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeTrackerRoute =
  AuthenticatedIncomeTrackerRouteImport.update({
    id: '/income-tracker',
    path: '/income-tracker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthCoachRoute =
  AuthenticatedGrowthCoachRouteImport.update({
    id: '/growth-coach',
    path: '/growth-coach',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGeneratorRoute = AuthenticatedGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlopAnalyserRoute =
  AuthenticatedFlopAnalyserRouteImport.update({
    id: '/flop-analyser',
    path: '/flop-analyser',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilmThisRoute = AuthenticatedFilmThisRouteImport.update({
  id: '/film-this',
  path: '/film-this',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEngagementBoosterRoute =
  AuthenticatedEngagementBoosterRouteImport.update({
    id: '/engagement-booster',
    path: '/engagement-booster',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeliverablesBuilderRoute =
  AuthenticatedDeliverablesBuilderRouteImport.update({
    id: '/deliverables-builder',
    path: '/deliverables-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCtaGeneratorRoute =
  AuthenticatedCtaGeneratorRouteImport.update({
    id: '/cta-generator',
    path: '/cta-generator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrollRoute = AuthenticatedBrollRouteImport.update({
  id: '/broll',
  path: '/broll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandHubRoute = AuthenticatedBrandHubRouteImport.update({
  id: '/brand-hub',
  path: '/brand-hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBioOptimiserRoute =
  AuthenticatedBioOptimiserRouteImport.update({
    id: '/bio-optimiser',
    path: '/bio-optimiser',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAffiliatesRoute = AuthenticatedAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin_/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrialRemindersRoute =
  ApiPublicHooksTrialRemindersRouteImport.update({
    id: '/api/public/hooks/trial-reminders',
    path: '/api/public/hooks/trial-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/app': typeof AuthenticatedAppRoute
  '/bio-optimiser': typeof AuthenticatedBioOptimiserRoute
  '/brand-hub': typeof AuthenticatedBrandHubRoute
  '/broll': typeof AuthenticatedBrollRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/cta-generator': typeof AuthenticatedCtaGeneratorRoute
  '/deliverables-builder': typeof AuthenticatedDeliverablesBuilderRoute
  '/engagement-booster': typeof AuthenticatedEngagementBoosterRoute
  '/film-this': typeof AuthenticatedFilmThisRoute
  '/flop-analyser': typeof AuthenticatedFlopAnalyserRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/growth-coach': typeof AuthenticatedGrowthCoachRoute
  '/income-tracker': typeof AuthenticatedIncomeTrackerRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/media-kit': typeof AuthenticatedMediaKitRoute
  '/motivation': typeof AuthenticatedMotivationRoute
  '/passive-ideas': typeof AuthenticatedPassiveIdeasRoute
  '/pin-optimiser': typeof AuthenticatedPinOptimiserRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/post-timing': typeof AuthenticatedPostTimingRoute
  '/profile-audit': typeof AuthenticatedProfileAuditRoute
  '/recycler': typeof AuthenticatedRecyclerRoute
  '/rejection-recovery': typeof AuthenticatedRejectionRecoveryRoute
  '/response-writer': typeof AuthenticatedResponseWriterRoute
  '/seo-keywords': typeof AuthenticatedSeoKeywordsRoute
  '/series-builder': typeof AuthenticatedSeriesBuilderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage-rights': typeof AuthenticatedUsageRightsRoute
  '/viral-lab': typeof AuthenticatedViralLabRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/success': typeof StoreSuccessRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/app': typeof AuthenticatedAppRoute
  '/bio-optimiser': typeof AuthenticatedBioOptimiserRoute
  '/brand-hub': typeof AuthenticatedBrandHubRoute
  '/broll': typeof AuthenticatedBrollRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/cta-generator': typeof AuthenticatedCtaGeneratorRoute
  '/deliverables-builder': typeof AuthenticatedDeliverablesBuilderRoute
  '/engagement-booster': typeof AuthenticatedEngagementBoosterRoute
  '/film-this': typeof AuthenticatedFilmThisRoute
  '/flop-analyser': typeof AuthenticatedFlopAnalyserRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/growth-coach': typeof AuthenticatedGrowthCoachRoute
  '/income-tracker': typeof AuthenticatedIncomeTrackerRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/media-kit': typeof AuthenticatedMediaKitRoute
  '/motivation': typeof AuthenticatedMotivationRoute
  '/passive-ideas': typeof AuthenticatedPassiveIdeasRoute
  '/pin-optimiser': typeof AuthenticatedPinOptimiserRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/post-timing': typeof AuthenticatedPostTimingRoute
  '/profile-audit': typeof AuthenticatedProfileAuditRoute
  '/recycler': typeof AuthenticatedRecyclerRoute
  '/rejection-recovery': typeof AuthenticatedRejectionRecoveryRoute
  '/response-writer': typeof AuthenticatedResponseWriterRoute
  '/seo-keywords': typeof AuthenticatedSeoKeywordsRoute
  '/series-builder': typeof AuthenticatedSeriesBuilderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage-rights': typeof AuthenticatedUsageRightsRoute
  '/viral-lab': typeof AuthenticatedViralLabRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/success': typeof StoreSuccessRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/affiliates': typeof AuthenticatedAffiliatesRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/bio-optimiser': typeof AuthenticatedBioOptimiserRoute
  '/_authenticated/brand-hub': typeof AuthenticatedBrandHubRoute
  '/_authenticated/broll': typeof AuthenticatedBrollRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/cta-generator': typeof AuthenticatedCtaGeneratorRoute
  '/_authenticated/deliverables-builder': typeof AuthenticatedDeliverablesBuilderRoute
  '/_authenticated/engagement-booster': typeof AuthenticatedEngagementBoosterRoute
  '/_authenticated/film-this': typeof AuthenticatedFilmThisRoute
  '/_authenticated/flop-analyser': typeof AuthenticatedFlopAnalyserRoute
  '/_authenticated/generator': typeof AuthenticatedGeneratorRoute
  '/_authenticated/growth-coach': typeof AuthenticatedGrowthCoachRoute
  '/_authenticated/income-tracker': typeof AuthenticatedIncomeTrackerRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/media-kit': typeof AuthenticatedMediaKitRoute
  '/_authenticated/motivation': typeof AuthenticatedMotivationRoute
  '/_authenticated/passive-ideas': typeof AuthenticatedPassiveIdeasRoute
  '/_authenticated/pin-optimiser': typeof AuthenticatedPinOptimiserRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/post-timing': typeof AuthenticatedPostTimingRoute
  '/_authenticated/profile-audit': typeof AuthenticatedProfileAuditRoute
  '/_authenticated/recycler': typeof AuthenticatedRecyclerRoute
  '/_authenticated/rejection-recovery': typeof AuthenticatedRejectionRecoveryRoute
  '/_authenticated/response-writer': typeof AuthenticatedResponseWriterRoute
  '/_authenticated/seo-keywords': typeof AuthenticatedSeoKeywordsRoute
  '/_authenticated/series-builder': typeof AuthenticatedSeriesBuilderRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/usage-rights': typeof AuthenticatedUsageRightsRoute
  '/_authenticated/viral-lab': typeof AuthenticatedViralLabRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/store_/$slug': typeof StoreSlugRoute
  '/store_/success': typeof StoreSuccessRoute
  '/_authenticated/admin_/products': typeof AuthenticatedAdminProductsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/refund'
    | '/signup'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/affiliates'
    | '/app'
    | '/bio-optimiser'
    | '/brand-hub'
    | '/broll'
    | '/business'
    | '/cta-generator'
    | '/deliverables-builder'
    | '/engagement-booster'
    | '/film-this'
    | '/flop-analyser'
    | '/generator'
    | '/growth-coach'
    | '/income-tracker'
    | '/insights'
    | '/invoices'
    | '/library'
    | '/media-kit'
    | '/motivation'
    | '/passive-ideas'
    | '/pin-optimiser'
    | '/planner'
    | '/portfolio'
    | '/post-timing'
    | '/profile-audit'
    | '/recycler'
    | '/rejection-recovery'
    | '/response-writer'
    | '/seo-keywords'
    | '/series-builder'
    | '/settings'
    | '/usage-rights'
    | '/viral-lab'
    | '/email/unsubscribe'
    | '/store/$slug'
    | '/store/success'
    | '/admin/products'
    | '/lovable/email/suppression'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/refund'
    | '/signup'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/affiliates'
    | '/app'
    | '/bio-optimiser'
    | '/brand-hub'
    | '/broll'
    | '/business'
    | '/cta-generator'
    | '/deliverables-builder'
    | '/engagement-booster'
    | '/film-this'
    | '/flop-analyser'
    | '/generator'
    | '/growth-coach'
    | '/income-tracker'
    | '/insights'
    | '/invoices'
    | '/library'
    | '/media-kit'
    | '/motivation'
    | '/passive-ideas'
    | '/pin-optimiser'
    | '/planner'
    | '/portfolio'
    | '/post-timing'
    | '/profile-audit'
    | '/recycler'
    | '/rejection-recovery'
    | '/response-writer'
    | '/seo-keywords'
    | '/series-builder'
    | '/settings'
    | '/usage-rights'
    | '/viral-lab'
    | '/email/unsubscribe'
    | '/store/$slug'
    | '/store/success'
    | '/admin/products'
    | '/lovable/email/suppression'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/refund'
    | '/signup'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/affiliates'
    | '/_authenticated/app'
    | '/_authenticated/bio-optimiser'
    | '/_authenticated/brand-hub'
    | '/_authenticated/broll'
    | '/_authenticated/business'
    | '/_authenticated/cta-generator'
    | '/_authenticated/deliverables-builder'
    | '/_authenticated/engagement-booster'
    | '/_authenticated/film-this'
    | '/_authenticated/flop-analyser'
    | '/_authenticated/generator'
    | '/_authenticated/growth-coach'
    | '/_authenticated/income-tracker'
    | '/_authenticated/insights'
    | '/_authenticated/invoices'
    | '/_authenticated/library'
    | '/_authenticated/media-kit'
    | '/_authenticated/motivation'
    | '/_authenticated/passive-ideas'
    | '/_authenticated/pin-optimiser'
    | '/_authenticated/planner'
    | '/_authenticated/portfolio'
    | '/_authenticated/post-timing'
    | '/_authenticated/profile-audit'
    | '/_authenticated/recycler'
    | '/_authenticated/rejection-recovery'
    | '/_authenticated/response-writer'
    | '/_authenticated/seo-keywords'
    | '/_authenticated/series-builder'
    | '/_authenticated/settings'
    | '/_authenticated/usage-rights'
    | '/_authenticated/viral-lab'
    | '/email/unsubscribe'
    | '/store_/$slug'
    | '/store_/success'
    | '/_authenticated/admin_/products'
    | '/lovable/email/suppression'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  StoreSlugRoute: typeof StoreSlugRoute
  StoreSuccessRoute: typeof StoreSuccessRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksTrialRemindersRoute: typeof ApiPublicHooksTrialRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/success': {
      id: '/store_/success'
      path: '/store/success'
      fullPath: '/store/success'
      preLoaderRoute: typeof StoreSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/$slug': {
      id: '/store_/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/viral-lab': {
      id: '/_authenticated/viral-lab'
      path: '/viral-lab'
      fullPath: '/viral-lab'
      preLoaderRoute: typeof AuthenticatedViralLabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage-rights': {
      id: '/_authenticated/usage-rights'
      path: '/usage-rights'
      fullPath: '/usage-rights'
      preLoaderRoute: typeof AuthenticatedUsageRightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/series-builder': {
      id: '/_authenticated/series-builder'
      path: '/series-builder'
      fullPath: '/series-builder'
      preLoaderRoute: typeof AuthenticatedSeriesBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seo-keywords': {
      id: '/_authenticated/seo-keywords'
      path: '/seo-keywords'
      fullPath: '/seo-keywords'
      preLoaderRoute: typeof AuthenticatedSeoKeywordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/response-writer': {
      id: '/_authenticated/response-writer'
      path: '/response-writer'
      fullPath: '/response-writer'
      preLoaderRoute: typeof AuthenticatedResponseWriterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rejection-recovery': {
      id: '/_authenticated/rejection-recovery'
      path: '/rejection-recovery'
      fullPath: '/rejection-recovery'
      preLoaderRoute: typeof AuthenticatedRejectionRecoveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recycler': {
      id: '/_authenticated/recycler'
      path: '/recycler'
      fullPath: '/recycler'
      preLoaderRoute: typeof AuthenticatedRecyclerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile-audit': {
      id: '/_authenticated/profile-audit'
      path: '/profile-audit'
      fullPath: '/profile-audit'
      preLoaderRoute: typeof AuthenticatedProfileAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post-timing': {
      id: '/_authenticated/post-timing'
      path: '/post-timing'
      fullPath: '/post-timing'
      preLoaderRoute: typeof AuthenticatedPostTimingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pin-optimiser': {
      id: '/_authenticated/pin-optimiser'
      path: '/pin-optimiser'
      fullPath: '/pin-optimiser'
      preLoaderRoute: typeof AuthenticatedPinOptimiserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/passive-ideas': {
      id: '/_authenticated/passive-ideas'
      path: '/passive-ideas'
      fullPath: '/passive-ideas'
      preLoaderRoute: typeof AuthenticatedPassiveIdeasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/motivation': {
      id: '/_authenticated/motivation'
      path: '/motivation'
      fullPath: '/motivation'
      preLoaderRoute: typeof AuthenticatedMotivationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media-kit': {
      id: '/_authenticated/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof AuthenticatedMediaKitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income-tracker': {
      id: '/_authenticated/income-tracker'
      path: '/income-tracker'
      fullPath: '/income-tracker'
      preLoaderRoute: typeof AuthenticatedIncomeTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth-coach': {
      id: '/_authenticated/growth-coach'
      path: '/growth-coach'
      fullPath: '/growth-coach'
      preLoaderRoute: typeof AuthenticatedGrowthCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generator': {
      id: '/_authenticated/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AuthenticatedGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flop-analyser': {
      id: '/_authenticated/flop-analyser'
      path: '/flop-analyser'
      fullPath: '/flop-analyser'
      preLoaderRoute: typeof AuthenticatedFlopAnalyserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/film-this': {
      id: '/_authenticated/film-this'
      path: '/film-this'
      fullPath: '/film-this'
      preLoaderRoute: typeof AuthenticatedFilmThisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engagement-booster': {
      id: '/_authenticated/engagement-booster'
      path: '/engagement-booster'
      fullPath: '/engagement-booster'
      preLoaderRoute: typeof AuthenticatedEngagementBoosterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliverables-builder': {
      id: '/_authenticated/deliverables-builder'
      path: '/deliverables-builder'
      fullPath: '/deliverables-builder'
      preLoaderRoute: typeof AuthenticatedDeliverablesBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cta-generator': {
      id: '/_authenticated/cta-generator'
      path: '/cta-generator'
      fullPath: '/cta-generator'
      preLoaderRoute: typeof AuthenticatedCtaGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/broll': {
      id: '/_authenticated/broll'
      path: '/broll'
      fullPath: '/broll'
      preLoaderRoute: typeof AuthenticatedBrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brand-hub': {
      id: '/_authenticated/brand-hub'
      path: '/brand-hub'
      fullPath: '/brand-hub'
      preLoaderRoute: typeof AuthenticatedBrandHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bio-optimiser': {
      id: '/_authenticated/bio-optimiser'
      path: '/bio-optimiser'
      fullPath: '/bio-optimiser'
      preLoaderRoute: typeof AuthenticatedBioOptimiserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates': {
      id: '/_authenticated/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AuthenticatedAffiliatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/products': {
      id: '/_authenticated/admin_/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-reminders': {
      id: '/api/public/hooks/trial-reminders'
      path: '/api/public/hooks/trial-reminders'
      fullPath: '/api/public/hooks/trial-reminders'
      preLoaderRoute: typeof ApiPublicHooksTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAffiliatesRoute: typeof AuthenticatedAffiliatesRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBioOptimiserRoute: typeof AuthenticatedBioOptimiserRoute
  AuthenticatedBrandHubRoute: typeof AuthenticatedBrandHubRoute
  AuthenticatedBrollRoute: typeof AuthenticatedBrollRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedCtaGeneratorRoute: typeof AuthenticatedCtaGeneratorRoute
  AuthenticatedDeliverablesBuilderRoute: typeof AuthenticatedDeliverablesBuilderRoute
  AuthenticatedEngagementBoosterRoute: typeof AuthenticatedEngagementBoosterRoute
  AuthenticatedFilmThisRoute: typeof AuthenticatedFilmThisRoute
  AuthenticatedFlopAnalyserRoute: typeof AuthenticatedFlopAnalyserRoute
  AuthenticatedGeneratorRoute: typeof AuthenticatedGeneratorRoute
  AuthenticatedGrowthCoachRoute: typeof AuthenticatedGrowthCoachRoute
  AuthenticatedIncomeTrackerRoute: typeof AuthenticatedIncomeTrackerRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMediaKitRoute: typeof AuthenticatedMediaKitRoute
  AuthenticatedMotivationRoute: typeof AuthenticatedMotivationRoute
  AuthenticatedPassiveIdeasRoute: typeof AuthenticatedPassiveIdeasRoute
  AuthenticatedPinOptimiserRoute: typeof AuthenticatedPinOptimiserRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedPostTimingRoute: typeof AuthenticatedPostTimingRoute
  AuthenticatedProfileAuditRoute: typeof AuthenticatedProfileAuditRoute
  AuthenticatedRecyclerRoute: typeof AuthenticatedRecyclerRoute
  AuthenticatedRejectionRecoveryRoute: typeof AuthenticatedRejectionRecoveryRoute
  AuthenticatedResponseWriterRoute: typeof AuthenticatedResponseWriterRoute
  AuthenticatedSeoKeywordsRoute: typeof AuthenticatedSeoKeywordsRoute
  AuthenticatedSeriesBuilderRoute: typeof AuthenticatedSeriesBuilderRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsageRightsRoute: typeof AuthenticatedUsageRightsRoute
  AuthenticatedViralLabRoute: typeof AuthenticatedViralLabRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAffiliatesRoute: AuthenticatedAffiliatesRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBioOptimiserRoute: AuthenticatedBioOptimiserRoute,
  AuthenticatedBrandHubRoute: AuthenticatedBrandHubRoute,
  AuthenticatedBrollRoute: AuthenticatedBrollRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedCtaGeneratorRoute: AuthenticatedCtaGeneratorRoute,
  AuthenticatedDeliverablesBuilderRoute: AuthenticatedDeliverablesBuilderRoute,
  AuthenticatedEngagementBoosterRoute: AuthenticatedEngagementBoosterRoute,
  AuthenticatedFilmThisRoute: AuthenticatedFilmThisRoute,
  AuthenticatedFlopAnalyserRoute: AuthenticatedFlopAnalyserRoute,
  AuthenticatedGeneratorRoute: AuthenticatedGeneratorRoute,
  AuthenticatedGrowthCoachRoute: AuthenticatedGrowthCoachRoute,
  AuthenticatedIncomeTrackerRoute: AuthenticatedIncomeTrackerRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMediaKitRoute: AuthenticatedMediaKitRoute,
  AuthenticatedMotivationRoute: AuthenticatedMotivationRoute,
  AuthenticatedPassiveIdeasRoute: AuthenticatedPassiveIdeasRoute,
  AuthenticatedPinOptimiserRoute: AuthenticatedPinOptimiserRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedPostTimingRoute: AuthenticatedPostTimingRoute,
  AuthenticatedProfileAuditRoute: AuthenticatedProfileAuditRoute,
  AuthenticatedRecyclerRoute: AuthenticatedRecyclerRoute,
  AuthenticatedRejectionRecoveryRoute: AuthenticatedRejectionRecoveryRoute,
  AuthenticatedResponseWriterRoute: AuthenticatedResponseWriterRoute,
  AuthenticatedSeoKeywordsRoute: AuthenticatedSeoKeywordsRoute,
  AuthenticatedSeriesBuilderRoute: AuthenticatedSeriesBuilderRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsageRightsRoute: AuthenticatedUsageRightsRoute,
  AuthenticatedViralLabRoute: AuthenticatedViralLabRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  StoreSlugRoute: StoreSlugRoute,
  StoreSuccessRoute: StoreSuccessRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksTrialRemindersRoute: ApiPublicHooksTrialRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
